config/routes.rb
NeLandmarks::Application.routes.draw do
  resources :landscapes

  

end

app/models/landscape.rb
class Landscape < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/landscapes_controller.rb
class LandscapesController < ApplicationController
  before_action :set_landscape, only: [:show, :edit, :update, :destroy]

  # GET /landscapes
  # GET /landscapes.json
  def index
    @landscapes = Landscape.all
  end

  # GET /landscapes/1
  # GET /landscapes/1.json
  def show
  end

  # GET /landscapes/new
  def new
    @landscape = Landscape.new
  end

  # GET /landscapes/1/edit
  def edit
  end

  # POST /landscapes
  # POST /landscapes.json
  def create
    @landscape = Landscape.new(landscape_params)

    respond_to do |format|
      if @landscape.save
        format.html { redirect_to @landscape, notice: 'Landscape was successfully created.' }
        format.json { render action: 'show', status: :created, location: @landscape }
      else
        format.html { render action: 'new' }
        format.json { render json: @landscape.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /landscapes/1
  # PATCH/PUT /landscapes/1.json
  def update
    respond_to do |format|
      if @landscape.update(landscape_params)
        format.html { redirect_to @landscape, notice: 'Landscape was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @landscape.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /landscapes/1
  # DELETE /landscapes/1.json
  def destroy
    @landscape.destroy
    respond_to do |format|
      format.html { redirect_to landscapes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_landscape
      @landscape = Landscape.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def landscape_params
      params.require(:landscape).permit(:latitude, :longitude, :name, :details)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landscapes_helper.rb
module LandscapesHelper
end

app/views/landscapes/_form.html.erb
<%= form_for(@landscape) do |f| %>
  <% if @landscape.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@landscape.errors.count, "error") %> prohibited this landscape from being saved:</h2>

      <ul>
      <% @landscape.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :details %><br>
    <%= f.text_area :details %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/landscapes/edit.html.erb
<h1>Editing landscape</h1>

<%= render 'form' %>

<%= link_to 'Show', @landscape %> |
<%= link_to 'Back', landscapes_path %>

app/views/landscapes/index.html.erb
<h1>Listing landscapes</h1>

<table>
  <thead>
    <tr>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Name</th>
      <th>Details</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @landscapes.each do |landscape| %>
      <tr>
        <td><%= landscape.latitude %></td>
        <td><%= landscape.longitude %></td>
        <td><%= landscape.name %></td>
        <td><%= landscape.details %></td>
        <td><%= link_to 'Show', landscape %></td>
        <td><%= link_to 'Edit', edit_landscape_path(landscape) %></td>
        <td><%= link_to 'Destroy', landscape, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Landscape', new_landscape_path %>

app/views/landscapes/new.html.erb
<h1>New landscape</h1>

<%= render 'form' %>

<%= link_to 'Back', landscapes_path %>

app/views/landscapes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Latitude:</strong>
  <%= @landscape.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @landscape.longitude %>
</p>

<p>
  <strong>Name:</strong>
  <%= @landscape.name %>
</p>

<p>
  <strong>Details:</strong>
  <%= @landscape.details %>
</p>

<%= link_to 'Edit', edit_landscape_path(@landscape) %> |
<%= link_to 'Back', landscapes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NeLandmarks</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>